StoreOnLine/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include
from django.urls import path

from StoreOnLine import views

urlpatterns = [
    path('usuarios/login', views.login_view, name='login'),
    path('usuarios/logout', views.logout_view, name='logout'),
    path('usuarios/register', views.register, name='register'),
    path('admin/', admin.site.urls),
    #productos esta en espanol debido a que esta es a que se muestra al ususario
    path('productos/', include('products.urls', namespace='products')),
    path('carrito/', include('carts.urls', namespace='carts')),
    path('orden/', include('orders.urls', namespace='orders')),
    path('direcciones/', include('shipping_address.urls', namespace='shipping_address')),
    path('codigos/', include('promo_codes.urls', namespace='codes')),
    path('pagos/', include('billing_profiles.urls', namespace='billing_profiles')),
]

#esta condicion nos permite mostrar nuestras imagenes en el template
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

billing_profiles/urls.py
from django.urls import path

from billing_profiles import views

app_name = 'billing_profiles'

urlpatterns = [
	path('nuevo', views.create, name='create'),
]

carts/urls.py
from django.urls import path

from carts import views

app_name = 'carts'

urlpatterns = [
    path('', views.cart, name='carts'),
    path('agregar', views.add, name='add'),
    path('eliminar', views.remove, name='remove'),
]

orders/urls.py
from django.urls import path

from orders import views

app_name = 'orders'

urlpatterns = [
    path('', views.order, name='order'),
    path('direccion', views.address, name='address'),
    path('seleccionar/direccion', views.select_address, name='select_address'),
    path('establecer/direccion/<int:pk>', views.check_address, name='check_address'),
    path('confirmacion', views.confirm, name='confirm'),
    path('cancelar', views.cancel, name='cancel'),
    path('completar', views.complete, name='complete'),
    path('completados', views.OrderListView.as_view(), name='completeds'),
]

promo_codes/urls.py
from django.urls import path

from promo_codes import views

app_name = 'promo_codes'

urlpatterns = [
	path('validar', views.validate, name='validar')
]

orders/models.py
import decimal
import uuid
from django.db import models
from django.db.models.signals import pre_save

from billing_profiles.models import BillingProfile
from carts.models import Cart
from orders.common import OrderStatus
from orders.common import choices
from promo_codes.models import PromoCode
from shipping_address.models import ShippingAddress
from users.models import User

class Order(models.Model):
    order_id = models.CharField(max_length=100, null=False, unique=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    status = models.CharField(max_length=50, choices=choices, default=OrderStatus.CREATED)#Enum
    shipping_total = models.DecimalField(default=5, max_digits=8, decimal_places=2)
    total = models.DecimalField(default=0, max_digits=8, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)
    shipping_address = models.ForeignKey(ShippingAddress, null=True, blank=True, on_delete=models.CASCADE)
    promo_code = models.OneToOneField(PromoCode, null=True, blank=True, on_delete=models.CASCADE)
    billing_profile = models.ForeignKey(BillingProfile, null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.order_id

    def apply_promo_code(self, promo_code):
        #la orden no posee un código promocional
        if self.promo_code is None:  
            #asignamos el código promocional a la orden          
            self.promo_code = promo_code
            self.save()

            #actualizamos el total
            self.update_total()
            promo_code.use()

    def get_or_set_shipping_address(self):
        #si la orden posee una direccion de envio entonces la retornamos
        if self.shipping_address:
            return self.shipping_address
        #sino obtiene la direccion del usuario
        shipping_address = self.user.shipping_address
        #si posee una direccion la actiualizamos
        if shipping_address:
            self.update_shipping_address(shipping_address)
        return shipping_address

    def update_shipping_address(self, shipping_address):
        self.shipping_address = shipping_address
        self.save()

    def cancel(self):
        self.status = OrderStatus.CANCELED
        self.save()  

    def complete(self):
        self.status = OrderStatus.COMPLETED
        self.save()
        
    def update_total(self):
        self.total = self.get_total()
        self.save()

    def get_discount(self):
        #si la orden posee un código promocional
        if self.promo_code:
            return self.promo_code.discount 

        #la orden no posee código promocional
        return 0

    def get_total(self):
        #total del carrito mas el costo de envio
        return self.cart.total + self.shipping_total - decimal.Decimal(self.get_discount())

    @property
    def description(self):
        return 'Comprar por ({}) productos '.format(
            self.cart.products.count()
        )

def set_order_id(sender, instance, *args, **kwargs):
    #si la orden no posee un order_id se la asignamos
    if not instance.order_id:
        instance.order_id = str(uuid.uuid4())

def set_total(sender, instance, *args, **kwargs):
    instance.total = instance.get_total()

pre_save.connect(set_order_id, sender=Order)
#antes que un objeto de tipo order se almacene se ejecuta el callback set_total
pre_save.connect(set_total,  sender=Order)

orders/views.py
import threading

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import transaction
from django.db.models.query import EmptyQuerySet
from django.shortcuts import redirect
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.views import generic

from carts.utils import destroy_cart
from carts.utils import get_or_create_cart
from charges.models import Charge
from orders.decorators import validate_cart_and_order
from orders.mails import Mail
from orders.models import Order
from orders.utils import breadcrumb
from orders.utils import destroy_order
from orders.utils import get_or_create_order
from shipping_address.models import ShippingAddress

@login_required(login_url='login')
@validate_cart_and_order
def order(request, cart, order):
    
    return render(request, 'orders/order.html', {
        'cart' : cart,
        'order': order,
        'breadcrumb' : breadcrumb,
    })

@login_required(login_url='login')
@validate_cart_and_order
def address(request, cart, order):
    
    shipping_address = order.get_or_set_shipping_address()
    can_choose_address = request.user.has_shipping_addresses()
    return render(request, 'orders/address.html', {
        'cart' : cart,
        'order' : order,
        'shipping_address':shipping_address,
        'can_choose_address': can_choose_address,
        #address es tru para que quede activa
        'breadcrumb' : breadcrumb(address=True)
    })

@login_required(login_url='login')
def select_address(request):
    #obtenemos todas las direcciones del usuario autenticado
    shipping_addresses = request.user.addresses
    return render(request, 'orders/select_address.html', {
        'breadcrumb': breadcrumb(address=True),
        #pasamos la vista al template
        'shipping_addresses':shipping_addresses
    })

@login_required(login_url='login')
@validate_cart_and_order
def check_address(request, cart, order, pk):

    #obtenemos la dirección que el usuario selecciona
    shipping_address = get_object_or_404(ShippingAddress, pk=pk)

    #validamos el usuario que es quien creo la dirección
    if request.user.id != shipping_address.user_id:
        #si es un usuario atacante
        return redirect('carts:cart')

    #actualizamos nuestra orden con el método update_shipping_address
    order.update_shipping_address(shipping_address)

    return redirect('orders:address')

@login_required(login_url='login')
@validate_cart_and_order
def confirm(request, cart, order):

    #Es necesario que la orden de compra posea una dirección
    shipping_address = order.shipping_address
    if shipping_address is None:
        #lo retornamos al template de dirección
        return redirect('orders:address')
    return render(request, 'orders/confirm.html', {
        'cart': cart,
        'order': order,
        'shipping_address': shipping_address,
        'breadcrumb': breadcrumb(address=True, confirmation=True),
    })

@login_required(login_url='login')
@validate_cart_and_order
def cancel(request, cart, order):

    #si el usuario es diferente del dueño de la orden
    if request.user.id != order.user_id:
        return redirect('carts:cart')

    order.cancel()
    destroy_cart(request)
    destroy_order(request)

    messages.error(request, 'Orden Cancelada')
    return redirect('products:index')

@login_required(login_url='login')
@validate_cart_and_order
def complete(request, cart, order):

    #si el usuario es diferente del dueño de la orden
    if request.user.id != order.user_id:
        return redirect('carts:cart')

    charge = Charge.objects.create_charge(order)
    #si el cargo se genera de manera exitosa
    if charge:
        with transaction.atomic():
            #damos la orden por completada
            order.complete()
            #con el parámetro indicamos la función o el método
            #que se va a ejecutar en segundo plano
            thread = threading.Thread(target=Mail.send_complete_order, args=(
                order, request.user
            ))
            #ejecutamos el método start
            thread.start()
        
            destroy_cart(request)
            destroy_order(request)

            messages.success(request, 'Compra completada exitosamente')
    return redirect('products:index')

class OrderListView(LoginRequiredMixin, generic.ListView):
    #redireccionamos a los usuarios anonimos a la vista login
    login_url = 'login'
    template_name = 'orders/orders.html'

    def get_queryset(self):
        #por el momento retorna una lista vacia
        return self.request.user.orders_completed()

orders/templates/orders/address.html
{% extends "base.html" %}

{% block breadcrumb %}
  {% include "orders/snippets/breadcrumb.html" %}
{% endblock breadcrumb %}

{% block content %}
  <div class="col">
    {% if shipping_address %}
      <div class="h3">
        Recoge el pedido en el punto de entrega
      </div>
      <div class="">
        {% include "shipping_addresses/snippets/shipping_address.html" %}
        <div class="mt-2">
          <a href="{% url 'orders:confirm' %}" class="btn btn-warning">Entregar en esta dirección</a>
        </div>
        {% if can_choose_address %}
          <div class="mt-2">
            <a href="{% url 'orders:select_address'%}">Otra dirección</a>
          </div>
        {% endif %}
      </div>
    {% else %}
      <div class="h3">
        Registra tu dirección de envío
      </div>
      <div class="">
        {% url 'orders:address' as next_url %}
        <a href="{% url 'shipping_address:create' %}?next={{ next_url }}">Nueva dirección de envío</a>
      </div>
    {% endif %}
  </div>
{% endblock content %}

orders/templates/orders/confirm.html
{% extends "base.html" %}

{% block breadcrumb %}
	{% include "orders/snippets/breadcrumb.html" %}
{% endblock breadcrumb %}

{% block content %}
	<div class="col-8">
		<div class="h3">
			confirma tu pedido
		</div>
		<div class="card">
			<div class="card-body">
				<div class="row">
					<div class="col-4">
						<div class="font-weight-bold">
							Dirección de envío
						</div>
						<div class="card-text">
							{{shipping_address.address}}
						</div>
						<div class="card-text">
							{{shipping_address.line1}}
						</div>
						<div class="card-text">
							{{shipping_address.reference}}
						</div>
						<div class="card-text">
							{{shipping_address.postal_code}}
						</div>
					</div>
					<div class="col-4">
						<div class="font-weight-bold">
							Método de pago
						</div>
						<div class="card-text">
							Trarjeta termomanción 4242
						</div>
					</div>
					<div class="col-4">
						<div class="font-weight-bold">
							Código promocional
						</div>
						<form id="promocode-form" action={% url 'promo_codes:validar' %}>
							<input type="text" name="code" value="{{ order.promo_code.code }}" class="form-control" placeholder="Código de promoción" {% if order.promo_code %} readonly {% endif %} >
						</form>
						<div class="text-success" id="promocode-success" style="font-size:14px">
							{% if order.promo_code %}
								Código aplicado exitosamente
							{% endif %}
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="mt-3">
			<div class="card">
				<div class="card-body">
					{% for product in cart.products.all %}
						{% include "orders/snippets/product.html" %}
					{% endfor %}				
				</div>
			</div>
		</div>
	</div>
	<div class="col">
		{% url 'orders:complete' as next_url %}
		{% include "orders/snippets/resume.html" with next_url=next_url %}
		<div class="mt-2">
			<a href="{% url 'orders:cancel' %}" class="btn btn-danger">Cancelar Orden</a>
		</div>
	</div>
{% endblock content %}

{% block javascript %}
	<script>
		const form = document.getElementById('promocode-form')
		form.addEventListener('submit', function(e){
			e.preventDefault()
			const input = this.code
			const code = input.value
			const url = this.action +"?code=" + code
			//actualizamos el total de la order
			const div_total = document.getElementById('order-toal')
			const div_success = document.getElementById('promocode-success')

			console.log(url)

			fetch(url)
				.then(response => response.json())
				.then(response => {
					// El servidor responde correctamente obtuvo 
					// al código promocional lo aplicó
					if(response.status === true){
						//success exito
						div_total.innerHTML = "$" + response.total
						div_success.classList.remove('text-danger')
						div_success.classList.add('text-success')
						div_success.innerHTML = 'Código aplicado exitosamente'

						input.readOnly = true
					} else{
						// cuando el servidor no puede encontrar el código promocional
						div_success.innerHTML = 'Código no valido'
						div_success.classList.remove('text-success')
						div_success.classList.add('text-danger')
					}
				})
		})
	</script>
{% endblock javascript %}

orders/templates/orders/order.html
{% extends "base.html" %}

{% block breadcrumb %}
  {% include "orders/snippets/breadcrumb.html" %}
{% endblock breadcrumb %}

{% block content %}
  <div class="col-8">
    <div class="h3">
      Revisa tu pedido
    </div>
    <div class="card">
      <div class="card-body">
        {% for product in cart.products.all %}
        <!-- como el snippet utiliza la variable product y esta variable ya se
            encuetra definida en el ciclo for  no se necesita with -->
          {% include "orders/snippets/product.html" %}
        {% endfor %}
      </div>
    </div>
  </div>
  <div class="col">
    {% url 'orders:address' as next_url %}
    {% include "orders/snippets/resume.html" with next_url=next_url %}
  </div>
{% endblock content %}

orders/templates/orders/orders.html
{% extends "base.html" %}

{% block content %}
	<div class="col">
		<div class="h3">
			Mis Pedidos
		</div>
		<div class="">
			{% for order in object_list %}
				{% include "orders/snippets/order.html" %}
			{% endfor %}
		</div>
{% endblock content %}

orders/templates/orders/select_address.html
{% extends "base.html" %}

{% block breadcrumb %}
	{% include "orders/snippets/breadcrumb.html" %}
{% endblock breadcrumb %}

{% block content %}
	<div class="col">
		<div class="h3">
			Selecciona una dirección de envío
		</div>
		<div class="mt-2">
			{% for shipping_address in shipping_addresses %}
				<div class="card mb-2">
					<div class="card-body">
						<h5 class="card-title">
							{{shipping_address.address}}
						</h5>
						<p class="card-title">{{shipping_address.postal_code}}</p>
						<a href="{% url 'orders:check_address' shipping_address.pk %}" class="btn btn-warning">Seleccionar dirección</a>
					</div>
				</div>
			{% endfor %}
		</div>
	</div>
{% endblock content %}