StoreOnLine/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include
from django.urls import path

from StoreOnLine import views

urlpatterns = [
    path('usuarios/login', views.login_view, name='login'),
    path('usuarios/logout', views.logout_view, name='logout'),
    path('usuarios/register', views.register, name='register'),
    path('admin/', admin.site.urls),
    #productos esta en espanol debido a que esta es a que se muestra al ususario
    path('productos/', include('products.urls', namespace='products')),
    path('carrito/', include('carts.urls', namespace='carts')),
    path('orden/', include('orders.urls', namespace='orders')),
    path('direcciones/', include('shipping_address.urls', namespace='shipping_address')),
    path('codigos/', include('promo_codes.urls', namespace='codes')),
    path('pagos/', include('billing_profiles.urls', namespace='billing_profiles')),
]

#esta condicion nos permite mostrar nuestras imagenes en el template
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

billing_profiles/urls.py
from django.urls import path

from billing_profiles import views

app_name = 'billing_profiles'

urlpatterns = [
	path('nuevo', views.create, name='create'),
]

carts/urls.py
from django.urls import path

from carts import views

app_name = 'carts'

urlpatterns = [
    path('', views.cart, name='carts'),
    path('agregar', views.add, name='add'),
    path('eliminar', views.remove, name='remove'),
]

billing_profiles/models.py
from django.db import models

from users.models import User

class BillingProfile(models.Model):
	#un usuario puede tener muchos métodos de pago
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	token = models.CharField(max_length=50, null=False, blank=False)
	card_id = models.CharField(max_length=50, null=False, blank=False)
	last4 = models.CharField(max_length=4, null=False, blank=False)
	brand = models.CharField(max_length=10, null=False, blank=False)
	default = models.BooleanField(default=False)
	creted_at = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.card_id

billing_profiles/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

@login_required(login_url='login')
def create(request):
	#El formulario ha realizado el submit
	if request.method == 'POST':
		#el formulario nos envía el token para generar una nueva tarjeta
		if request.POST.get('sripeToken'):
			#antes de crear la tarjeta es necesario validar si el usuario
			#posee o no un cliente en stripe en caso de no poseer es necesario
			#dar de alta o crear uno nuevo, inocamos el método que creamos antes
			if not request.user.has_customer():
				#en caso no posea un cliente
				request.user.create_customer_id()
				
	return render(request, 'billing_profiles/create.html', {
		'stripe_public_key':settings.STRIPE_PUBLIC_KEY
	})

billing_profiles/templates/billing_profiles/create.html
{% extends "base.html" %}
{% load static %}

{% block css %}
	<link rel="stylesheet" href="{% static 'css/stripe.css'%}">
{% endblock css %}

{% block content %}
	<div class="col">
		<div class="h3">
			Nuevo método de pago
		</div>
		<div class="">
			<!-- Display a payment form -->
		    <form action="{% url 'billing_profiles:create' %}" method="post" id="payment-form">
		    	<div class="form-group">
		    		<div class="form-control" id="card-element" style="height:2.4em; padding-top:.7em">
		    			<!--Stripe.js injects the Card Element-->
		    		</div>
		    		<div class="" id="card-errors" role="alert">
		    			
		    		</div>
		    	</div>
		      	<button type="submit" class="btn btn-primary">Agregar Nueva Tarjeta</button>
		    </form>
		</div>
	</div>
{% endblock content %}

{% block javascript %}
	<script src="https://js.stripe.com/v3/"></script>
	<script src="https://js.stripe.com/v3/"></script>
	<script src="{% static 'js/stripe.js' %}"></script>
{% endblock javascript %}