StoreOnLine/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include
from django.urls import path

from StoreOnLine import views

urlpatterns = [
    path('usuarios/login', views.login_view, name='login'),
    path('usuarios/logout', views.logout_view, name='logout'),
    path('usuarios/register', views.register, name='register'),
    path('admin/', admin.site.urls),
    #productos esta en espanol debido a que esta es a que se muestra al ususario
    path('productos/', include('products.urls', namespace='products')),
    path('carrito/', include('carts.urls', namespace='carts')),
    path('orden/', include('orders.urls', namespace='orders')),
    path('direcciones/', include('shipping_address.urls', namespace='shipping_address')),
    path('codigos/', include('promo_codes.urls', namespace='codes')),
    path('pagos/', include('billing_profiles.urls', namespace='billing_profiles')),
]

#esta condicion nos permite mostrar nuestras imagenes en el template
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

billing_profiles/urls.py
from django.urls import path

from billing_profiles import views

app_name = 'billing_profiles'

urlpatterns = [
	path('nuevo', views.create, name='create'),
]

carts/urls.py
from django.urls import path

from carts import views

app_name = 'carts'

urlpatterns = [
    path('', views.cart, name='carts'),
    path('agregar', views.add, name='add'),
    path('eliminar', views.remove, name='remove'),
]

orders/urls.py
from django.urls import path

from orders import views

app_name = 'orders'

urlpatterns = [
    path('', views.order, name='order'),
    path('direccion', views.address, name='address'),
    path('seleccionar/direccion', views.select_address, name='select_address'),
    path('establecer/direccion/<int:pk>', views.check_address, name='check_address'),
    path('confirmacion', views.confirm, name='confirm'),
    path('cancelar', views.cancel, name='cancel'),
    path('completar', views.complete, name='complete'),
    path('completados', views.OrderListView.as_view(), name='completeds'),
]

products/urls.py
from django.urls import path

from products import views

app_name = 'products'

urlpatterns = [
    path('', views.ProductListView.as_view(), name='index'),
    path('search', views.ProductSearchView.as_view(), name='search'),
    #Estamos indicando que vamos abuscar porelatributo slug
    path('<slug:slug>', views.ProductDetailView.as_view(), name='product'),
]

shipping_address/urls.py
from django.urls import path

from shipping_address import views

app_name = 'shipping_address'

urlpatterns = [
    path('', views.ShippingAddressListView.as_view(), name='shipping_addresses'),
    path('nuevo', views.create, name='create'),
    path('editar/<int:pk>', views.ShippingAddressUpdateView.as_view(), name='update'),
    path('eliminar/<int:pk>', views.ShippingAddressDeleteView.as_view(), name='delete'),
    path('default/<int:pk>', views.default, name='default'),
]

templates/base.html
{% load static %}
{# Load the tag library #}
{% load bootstrap4 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock title %}</title>
    {% if stripe_public_key %}
      <meta name="stripe_public_key" content="{{ stripe_public_key }}">
    {% endif %}
    {% block css %}
    {% endblock css %}
  </head>
  <body>
    {% include "navbar.html" %}
    <div class="container">
      {% include "message.html" %}
      {% block breadcrumb %}        
      {% endblock breadcrumb %}
      <div class="row mt-3">
        {% block content %}
        {% endblock content %}
      </div>
    </div>
  </body>
  <script src="https://kit.fontawesome.com/ed5652a487.js" crossorigin="anonymous"></script>
  
  {% block javascript %}
  {% endblock javascript %}
</html>

templates/index.html
{% extends "base.html" %}
{% load static %}
{% block title %}{{title}}{% endblock title %}
{% block content %}
  <div class="col">
    <h4 class="text-center">{{message}}</h4>
    {% include "snippet/s_search.html" %}
    {% if is_paginated %}
    	<div class="mt-2">
    		<ul class="pagination">
    			{% if page_obj.has_previous %}
    				<li class="page-item">
    					<a href="?page={{ page_obj.previous_page_number}}" class="page-link">Previous</a>
    				</li>
    			{% else %}
    				<li class="page-item disabled">
    					<a href="#" class="page-link">Previous</a>
    				</li>
    			{% endif %}
    			{% for i in paginator.page_range %}
	    				<li class="page-item {% if page_obj.number == i %} active {% endif %}">
    						<a href="?page={{i}}" class="page-link">{{i}}</a>
    					</li>	    			
    			{% endfor %}

    			{% if page_obj.has_next %}
    				<li class="page-item">
    					<a href="?page={{ page_obj.next_page_number}}" class="page-link">Next</a>
    				</li>
    			{% else %}
    				<li class="page-item disabled">
    					<a href="#" class="page-link">Next</a>
    				</li>
    			{% endif %}
    		</ul>
    	</div>
    {% endif %}
    {% include "snippet/s_list.html" %}
   
  </div>
    
{% endblock content %}

templates/message.html
{% if messages %}
  {% for message in messages %}
    <div class="alert {% if message.tags == 'success' %} alert-success {% else %} alert-danger {% endif %}">
      <button type="button" class="close" data-dismiss="alert">X</button>
      {{ message }}
    </div>
  {% endfor %}
{% endif %}

templates/navbar.html
{% url 'login' as login %}
{% url 'register' as register %}
{% url 'carts:carts' as cart %}
{% url 'shipping_address:shipping_addresses' as shipping_addresses %}
{% url 'orders:completeds' as completeds %}
{% url 'billing_profiles:billing_profiles' as billing_profiles %}

<nav class="navbar navbar-expand-md bg-dark navbar-dark">
  <a href="{% url 'products:index' %}" class="navbar-brand">Store On Line</a>
  <!-- para que labarra de navegacion sea response -->
  <!-- este boton solo aparece cuando la pantalla sea pequena -->
  <button type="button" name="button" class="navbar-toggler navbar-toggler-right" data-toggle="collapse" data-target="#navb">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div id="navb" class="navbar-collapse hide">
    <ul class="navbar-nav">
      <li class="nav-item {% if request.path == cart %} active {% endif %}">
        <a class="nav-link" href='{{ cart }}'>
          Mi carrito <span class="fas fa-shopping-cart"></span>
        </a>
      </li>
      {% if user.is_authenticated %}
        <li class="nav-item {% if request.path == shipping_addresses %} active {% endif %}">
          <a class="nav-link" href='{{ shipping_addresses }}'>
            Mis  Direcciones <span class="fas fa-location-arrow"></span>
          </a>
        </li>
        <li class="nav-item {% if request.path == completeds %} active {% endif %}">
          <a class="nav-link" href='{{ completeds }}'>
            Mis  Pedidos <span class="fas fa-shipping-fast"></span>
          </a>
        </li>
        <li class="nav-item {% if request.path == billing_profiles %} active {% endif %}">
          <a class="nav-link" href='{{ billing_profiles }}'>
            Mis Métodos de pago <span class="fab fa-cc-stripe"></span>
          </a>
        </li>
      {% endif %}
    </ul>
    <ul class="nav navbar-nav ml-auto">
      {% if user.is_authenticated %}
        <li class="navbar-item">
          <a href="{% url 'logout' %}" class="nav-link">
            <span class="fas fa-sign-out-alt"></span>
            logout</a>
        </li>
        {% else %}
          <li class="navbar-item {% if request.path == login %}active{% endif %}">
            <a href="{{login}}" class="nav-link">
              <span class="fas fa-user"></span>
              login</a>
          </li>
          <li class="navbar-item {% if request.path == register %}active{% endif %}">
            <a href="{{register}}" class="nav-link">
              <span class="fas fa-sign-in-alt"></span>
              Registro</a>
          </li>
        {% endif %}
    </ul>
  </div>
</nav>